version: '3.8'
services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - microservices-net

  product-service:
    build: ./product-service
    depends_on:
      - discovery-service
      - mongodb
    networks:
      - microservices-net

  booking-microservice:
    build: ./booking-microservice
    depends_on:
      - discovery-service
      - mysql
    networks:
      - microservices-net

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    networks:
      - microservices-net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty2006.
      MYSQL_DATABASE: bookingdb
    ports:
      - "3306:3306"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
