version: '3.8'

services:
  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - spring-network
    environment:
      - EUREKA_SERVER_URL=http://8761-old-forest-22658171.in-ws1.runcode.io/eureka/

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - discovery-service
    environment:
      - EUREKA_SERVER_URL=http://8761-old-forest-22658171.in-ws1.runcode.io/eureka/

networks:
  spring-network:
    driver: bridge
